---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        image: queengarcia/payment-ms:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: payment-ms
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: payment-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081 #change for microservice
